name: dotenv
channels:
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - pandas
  - astropy>3.2.1
  - conda-forge::lightkurve
  - h5py
  - conda-forge::pymc3
  - conda-forge::celerite
  - matplotlib
  - nb_conda_kernels
  - ipython
  - pip
  - pip:
    - wandb
    - tqdm
    - pyprojroot
    - black
    - pylint
    - isort
    - flake8
    - mypy
    - pytest
    - pydocstyle
    - ipykernel
    - corner